# Generated by Django 4.0.5 on 2022-10-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='username'),
        ),
    ]
