# Generated by Django 4.0.5 on 2022-10-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='uploads/default-avatar.png', upload_to='uploads/%Y/%m/%d'),
        ),
    ]
