# Generated by Django 4.0.5 on 2022-10-10 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_myuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='located',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('detail_country', models.CharField(blank=True, default='', max_length=500)),
                ('located_type', models.IntegerField(blank=True, default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
