# Generated by Django 4.0.5 on 2022-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_located'),
    ]

    operations = [
        migrations.AddField(
            model_name='located',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='located',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
