# Generated by Django 4.0.5 on 2022-10-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_user_id_located_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='located',
            name='is_use',
            field=models.BooleanField(default=True),
        ),
    ]
