# Generated by Django 4.0.5 on 2022-10-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_located_is_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='located',
            old_name='is_use',
            new_name='is_default',
        ),
    ]
