# Generated by Django 4.0.5 on 2022-10-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_is_use_located_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='located',
            name='located_type',
            field=models.IntegerField(default=0),
        ),
    ]
