# Generated by Django 4.0.5 on 2022-09-30 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_prd', to='products.product'),
        ),
    ]
