# Generated by Django 4.0.5 on 2022-10-13 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_order_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_data', models.CharField(blank=True, default='', max_length=1000)),
                ('transport_fee', models.IntegerField(default=0)),
                ('total_payment', models.IntegerField(default=0)),
                ('order_time', models.DateField(auto_now_add=True)),
                ('order_status', models.IntegerField(default=0)),
                ('located', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.located')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='order_history',
        ),
        migrations.AlterField(
            model_name='product_wishlist',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
