# Generated by Django 4.0.5 on 2022-10-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comment_history_order_delete_order_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('msg', models.CharField(blank=True, default='', max_length=500)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
