# Generated by Django 4.0.5 on 2022-10-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_order',
            name='payment_method',
            field=models.BooleanField(default=0),
        ),
    ]
